"""
Expanded NER Training Data for Voice Assistant Commands
Contains 500+ diverse examples with multiple entity types
"""

TRAINING_DATA = [
    # App opening commands (50 examples)
    ("open chrome", {"entities": [(5, 11, "APP_NAME")]}),
    ("launch firefox", {"entities": [(7, 14, "APP_NAME")]}),
    ("start notepad", {"entities": [(6, 13, "APP_NAME")]}),
    ("run calculator", {"entities": [(4, 14, "APP_NAME")]}),
    ("open microsoft word", {"entities": [(5, 20, "APP_NAME")]}),
    ("launch spotify", {"entities": [(7, 14, "APP_NAME")]}),
    ("start discord", {"entities": [(6, 13, "APP_NAME")]}),
    ("open vscode", {"entities": [(5, 11, "APP_NAME")]}),
    ("launch steam", {"entities": [(7, 12, "APP_NAME")]}),
    ("run excel", {"entities": [(4, 9, "APP_NAME")]}),
    ("open photoshop", {"entities": [(5, 15, "APP_NAME")]}),
    ("launch vlc", {"entities": [(7, 10, "APP_NAME")]}),
    ("start skype", {"entities": [(6, 11, "APP_NAME")]}),
    ("run zoom", {"entities": [(4, 8, "APP_NAME")]}),
    ("open slack", {"entities": [(5, 10, "APP_NAME")]}),
    ("launch teams", {"entities": [(7, 12, "APP_NAME")]}),
    ("start outlook", {"entities": [(6, 13, "APP_NAME")]}),
    ("open edge", {"entities": [(5, 9, "APP_NAME")]}),
    ("run safari", {"entities": [(4, 10, "APP_NAME")]}),
    ("launch itunes", {"entities": [(7, 13, "APP_NAME")]}),
    ("open netflix", {"entities": [(5, 12, "APP_NAME")]}),
    ("start youtube", {"entities": [(6, 13, "APP_NAME")]}),
    ("run whatsapp", {"entities": [(4, 12, "APP_NAME")]}),
    ("open telegram", {"entities": [(5, 13, "APP_NAME")]}),
    ("launch facebook", {"entities": [(7, 15, "APP_NAME")]}),
    ("start twitter", {"entities": [(6, 13, "APP_NAME")]}),
    ("open instagram", {"entities": [(5, 14, "APP_NAME")]}),
    ("run tiktok", {"entities": [(4, 10, "APP_NAME")]}),
    ("launch amazon", {"entities": [(7, 13, "APP_NAME")]}),
    ("open gmail", {"entities": [(5, 10, "APP_NAME")]}),
    ("start calendar", {"entities": [(6, 14, "APP_NAME")]}),
    ("run maps", {"entities": [(4, 8, "APP_NAME")]}),
    ("open weather", {"entities": [(5, 12, "APP_NAME")]}),
    ("launch camera", {"entities": [(7, 13, "APP_NAME")]}),
    ("start music", {"entities": [(6, 11, "APP_NAME")]}),
    ("open photos", {"entities": [(5, 11, "APP_NAME")]}),
    ("run clock", {"entities": [(4, 9, "APP_NAME")]}),
    ("launch settings", {"entities": [(7, 15, "APP_NAME")]}),
    ("start files", {"entities": [(6, 11, "APP_NAME")]}),
    ("open drive", {"entities": [(5, 10, "APP_NAME")]}),
    ("run terminal", {"entities": [(4, 12, "APP_NAME")]}),
    ("launch browser", {"entities": [(7, 14, "APP_NAME")]}),
    ("start editor", {"entities": [(6, 12, "APP_NAME")]}),
    ("open paint", {"entities": [(5, 10, "APP_NAME")]}),
    ("run wordpad", {"entities": [(4, 11, "APP_NAME")]}),
    ("launch powerpoint", {"entities": [(7, 17, "APP_NAME")]}),
    ("start access", {"entities": [(6, 12, "APP_NAME")]}),
    ("open publisher", {"entities": [(5, 14, "APP_NAME")]}),
    ("run onenote", {"entities": [(4, 11, "APP_NAME")]}),
    ("launch evernote", {"entities": [(7, 15, "APP_NAME")]}),
    ("start notion", {"entities": [(6, 12, "APP_NAME")]}),
    ("open trello", {"entities": [(5, 11, "APP_NAME")]}),

    # Search commands (80 examples)
    ("search for pizza", {"entities": [(11, 16, "QUERY")]}),
    ("find restaurants near me", {"entities": [(5, 16, "QUERY")]}),
    ("look up python programming", {"entities": [(8, 26, "QUERY")]}),
    ("google machine learning", {"entities": [(7, 23, "QUERY")]}),
    ("search weather forecast", {"entities": [(7, 23, "QUERY")]}),
    ("find hotels in paris", {"entities": [(5, 11, "QUERY")]}),
    ("look up recipes", {"entities": [(8, 15, "QUERY")]}),
    ("search for jobs", {"entities": [(11, 15, "QUERY")]}),
    ("find movies playing", {"entities": [(5, 18, "QUERY")]}),
    ("google current news", {"entities": [(7, 18, "QUERY")]}),
    ("search local events", {"entities": [(7, 18, "QUERY")]}),
    ("find nearby gas stations", {"entities": [(5, 23, "QUERY")]}),
    ("look up stock prices", {"entities": [(8, 20, "QUERY")]}),
    ("search for flights", {"entities": [(11, 18, "QUERY")]}),
    ("find vegan recipes", {"entities": [(5, 18, "QUERY")]}),
    ("google cryptocurrency", {"entities": [(7, 22, "QUERY")]}),
    ("search tech reviews", {"entities": [(7, 18, "QUERY")]}),
    ("find hiking trails", {"entities": [(5, 18, "QUERY")]}),
    ("look up medical information", {"entities": [(8, 27, "QUERY")]}),
    ("search for apartments", {"entities": [(11, 21, "QUERY")]}),
    ("find coffee shops", {"entities": [(5, 17, "QUERY")]}),
    ("google quantum physics", {"entities": [(7, 22, "QUERY")]}),
    ("search artificial intelligence", {"entities": [(7, 29, "QUERY")]}),
    ("find online courses", {"entities": [(5, 19, "QUERY")]}),
    ("look up climate change", {"entities": [(8, 22, "QUERY")]}),
    ("search for books", {"entities": [(11, 16, "QUERY")]}),
    ("find workout routines", {"entities": [(5, 21, "QUERY")]}),
    ("google space exploration", {"entities": [(7, 24, "QUERY")]}),
    ("search renewable energy", {"entities": [(7, 23, "QUERY")]}),
    ("find travel destinations", {"entities": [(5, 24, "QUERY")]}),
    ("look up movie reviews", {"entities": [(8, 21, "QUERY")]}),
    ("search concert tickets", {"entities": [(7, 22, "QUERY")]}),
    ("find sports scores", {"entities": [(5, 18, "QUERY")]}),
    ("google digital marketing", {"entities": [(7, 24, "QUERY")]}),
    ("search cybersecurity", {"entities": [(7, 21, "QUERY")]}),
    ("find cloud computing", {"entities": [(5, 20, "QUERY")]}),
    ("look up internet of things", {"entities": [(8, 26, "QUERY")]}),
    ("search virtual reality", {"entities": [(7, 22, "QUERY")]}),
    ("find augmented reality", {"entities": [(5, 22, "QUERY")]}),
    ("google machine learning algorithms", {"entities": [(7, 33, "QUERY")]}),
    ("search data science tutorials", {"entities": [(7, 28, "QUERY")]}),
    ("find web development tools", {"entities": [(5, 25, "QUERY")]}),
    ("look up mobile app development", {"entities": [(8, 30, "QUERY")]}),
    ("search for programming languages", {"entities": [(11, 32, "QUERY")]}),
    ("find database management", {"entities": [(5, 24, "QUERY")]}),
    ("google artificial neural networks", {"entities": [(7, 32, "QUERY")]}),
    ("search computer vision", {"entities": [(7, 22, "QUERY")]}),
    ("find natural language processing", {"entities": [(5, 31, "QUERY")]}),
    ("look up deep learning", {"entities": [(8, 21, "QUERY")]}),
    ("search blockchain technology", {"entities": [(7, 27, "QUERY")]}),
    ("find cryptocurrency exchanges", {"entities": [(5, 28, "QUERY")]}),
    ("google startup funding", {"entities": [(7, 22, "QUERY")]}),
    ("search venture capital", {"entities": [(7, 22, "QUERY")]}),
    ("find angel investors", {"entities": [(5, 20, "QUERY")]}),
    ("look up business models", {"entities": [(8, 23, "QUERY")]}),
    ("search marketing strategies", {"entities": [(7, 26, "QUERY")]}),
    ("find social media tools", {"entities": [(5, 22, "QUERY")]}),
    ("google content creation", {"entities": [(7, 24, "QUERY")]}),
    ("search seo optimization", {"entities": [(7, 23, "QUERY")]}),
    ("find email marketing", {"entities": [(5, 20, "QUERY")]}),
    ("look up analytics tools", {"entities": [(8, 23, "QUERY")]}),
    ("search project management", {"entities": [(7, 25, "QUERY")]}),
    ("find productivity apps", {"entities": [(5, 22, "QUERY")]}),
    ("google time management", {"entities": [(7, 22, "QUERY")]}),
    ("search collaboration tools", {"entities": [(7, 25, "QUERY")]}),
    ("find remote work solutions", {"entities": [(5, 26, "QUERY")]}),
    ("look up freelance platforms", {"entities": [(8, 26, "QUERY")]}),
    ("search gig economy", {"entities": [(7, 18, "QUERY")]}),
    ("find side hustle ideas", {"entities": [(5, 22, "QUERY")]}),
    ("google passive income", {"entities": [(7, 21, "QUERY")]}),
    ("search investment opportunities", {"entities": [(7, 29, "QUERY")]}),
    ("find real estate deals", {"entities": [(5, 22, "QUERY")]}),
    ("look up stock market analysis", {"entities": [(8, 29, "QUERY")]}),
    ("search cryptocurrency trends", {"entities": [(7, 27, "QUERY")]}),
    ("find nft marketplaces", {"entities": [(5, 21, "QUERY")]}),
    ("google metaverse", {"entities": [(7, 16, "QUERY")]}),
    ("search web3 technologies", {"entities": [(7, 24, "QUERY")]}),
    ("find decentralized finance", {"entities": [(5, 26, "QUERY")]}),
    ("look up smart contracts", {"entities": [(8, 23, "QUERY")]}),
    ("search defi protocols", {"entities": [(7, 21, "QUERY")]}),
    ("find yield farming", {"entities": [(5, 18, "QUERY")]}),

    # Location-based commands (60 examples)
    ("what's the weather in New York", {"entities": [(23, 31, "LOCATION")]}),
    ("show me restaurants in London", {"entities": [(23, 29, "LOCATION")]}),
    ("find hotels in Paris", {"entities": [(14, 19, "LOCATION")]}),
    ("directions to Tokyo", {"entities": [(14, 19, "LOCATION")]}),
    ("weather in Mumbai", {"entities": [(11, 17, "LOCATION")]}),
    ("restaurants near Delhi", {"entities": [(17, 22, "LOCATION")]}),
    ("hotels in Sydney", {"entities": [(10, 16, "LOCATION")]}),
    ("directions to Berlin", {"entities": [(14, 20, "LOCATION")]}),
    ("weather in Rome", {"entities": [(11, 15, "LOCATION")]}),
    ("restaurants in Barcelona", {"entities": [(14, 23, "LOCATION")]}),
    ("find hotels in Amsterdam", {"entities": [(14, 23, "LOCATION")]}),
    ("directions to Vienna", {"entities": [(14, 20, "LOCATION")]}),
    ("weather in Prague", {"entities": [(11, 17, "LOCATION")]}),
    ("restaurants near Budapest", {"entities": [(17, 25, "LOCATION")]}),
    ("hotels in Warsaw", {"entities": [(10, 16, "LOCATION")]}),
    ("directions to Moscow", {"entities": [(14, 20, "LOCATION")]}),
    ("weather in Beijing", {"entities": [(11, 18, "LOCATION")]}),
    ("restaurants in Shanghai", {"entities": [(14, 23, "LOCATION")]}),
    ("find hotels in Singapore", {"entities": [(14, 23, "LOCATION")]}),
    ("directions to Bangkok", {"entities": [(14, 21, "LOCATION")]}),
    ("weather in Dubai", {"entities": [(11, 16, "LOCATION")]}),
    ("restaurants near Istanbul", {"entities": [(17, 25, "LOCATION")]}),
    ("hotels in Cairo", {"entities": [(10, 15, "LOCATION")]}),
    ("directions to Cape Town", {"entities": [(14, 23, "LOCATION")]}),
    ("weather in Rio de Janeiro", {"entities": [(11, 25, "LOCATION")]}),
    ("restaurants in Buenos Aires", {"entities": [(14, 27, "LOCATION")]}),
    ("find hotels in Mexico City", {"entities": [(14, 25, "LOCATION")]}),
    ("directions to Toronto", {"entities": [(14, 21, "LOCATION")]}),
    ("weather in Vancouver", {"entities": [(11, 20, "LOCATION")]}),
    ("restaurants near Los Angeles", {"entities": [(17, 29, "LOCATION")]}),
    ("hotels in Chicago", {"entities": [(10, 17, "LOCATION")]}),
    ("directions to Houston", {"entities": [(14, 21, "LOCATION")]}),
    ("weather in Phoenix", {"entities": [(11, 18, "LOCATION")]}),
    ("restaurants in Philadelphia", {"entities": [(14, 27, "LOCATION")]}),
    ("find hotels in San Francisco", {"entities": [(14, 27, "LOCATION")]}),
    ("directions to Seattle", {"entities": [(14, 21, "LOCATION")]}),
    ("weather in Boston", {"entities": [(11, 17, "LOCATION")]}),
    ("restaurants near Austin", {"entities": [(17, 23, "LOCATION")]}),
    ("hotels in Denver", {"entities": [(10, 16, "LOCATION")]}),
    ("directions to Miami", {"entities": [(14, 19, "LOCATION")]}),
    ("weather in Atlanta", {"entities": [(11, 18, "LOCATION")]}),
    ("restaurants in Nashville", {"entities": [(14, 23, "LOCATION")]}),
    ("find hotels in Portland", {"entities": [(14, 22, "LOCATION")]}),
    ("directions to Las Vegas", {"entities": [(14, 23, "LOCATION")]}),
    ("weather in Orlando", {"entities": [(11, 18, "LOCATION")]}),
    ("restaurants near Salt Lake City", {"entities": [(17, 32, "LOCATION")]}),
    ("hotels in Pittsburgh", {"entities": [(10, 20, "LOCATION")]}),
    ("directions to Cincinnati", {"entities": [(14, 25, "LOCATION")]}),
    ("weather in Cleveland", {"entities": [(11, 20, "LOCATION")]}),
    ("restaurants in Tampa", {"entities": [(14, 19, "LOCATION")]}),
    ("find hotels in Raleigh", {"entities": [(14, 21, "LOCATION")]}),
    ("directions to Sacramento", {"entities": [(14, 25, "LOCATION")]}),
    ("weather in Kansas City", {"entities": [(11, 23, "LOCATION")]}),
    ("restaurants near Colorado Springs", {"entities": [(17, 34, "LOCATION")]}),
    ("hotels in Omaha", {"entities": [(10, 15, "LOCATION")]}),
    ("directions to Tulsa", {"entities": [(14, 19, "LOCATION")]}),
    ("weather in Albuquerque", {"entities": [(11, 23, "LOCATION")]}),
    ("restaurants in Fresno", {"entities": [(14, 20, "LOCATION")]}),
    ("find hotels in Colorado", {"entities": [(14, 22, "LOCATION")]}),
    ("directions to Virginia", {"entities": [(14, 22, "LOCATION")]}),
    ("weather in Florida", {"entities": [(11, 18, "LOCATION")]}),
    ("restaurants near Texas", {"entities": [(17, 22, "LOCATION")]}),
    ("hotels in California", {"entities": [(10, 20, "LOCATION")]}),
    ("directions to New Jersey", {"entities": [(14, 24, "LOCATION")]}),
    ("weather in Pennsylvania", {"entities": [(11, 23, "LOCATION")]}),
    ("restaurants in Illinois", {"entities": [(14, 22, "LOCATION")]}),

    # Date/Time commands (70 examples)
    ("remind me on January 1st", {"entities": [(14, 25, "DATE")]}),
    ("schedule meeting tomorrow", {"entities": [(17, 25, "DATE")]}),
    ("set alarm for next week", {"entities": [(14, 23, "DATE")]}),
    ("calendar event on Friday", {"entities": [(18, 24, "DATE")]}),
    ("birthday on March 15th", {"entities": [(12, 23, "DATE")]}),
    ("remind me on Monday", {"entities": [(14, 20, "DATE")]}),
    ("schedule for Tuesday", {"entities": [(13, 20, "DATE")]}),
    ("set alarm for Wednesday", {"entities": [(14, 23, "DATE")]}),
    ("calendar event on Thursday", {"entities": [(18, 26, "DATE")]}),
    ("meeting on Saturday", {"entities": [(11, 19, "DATE")]}),
    ("remind me on Sunday", {"entities": [(14, 20, "DATE")]}),
    ("schedule for next Monday", {"entities": [(13, 24, "DATE")]}),
    ("set alarm for next Tuesday", {"entities": [(14, 26, "DATE")]}),
    ("calendar event next Wednesday", {"entities": [(15, 29, "DATE")]}),
    ("meeting next Thursday", {"entities": [(8, 22, "DATE")]}),
    ("remind me next Friday", {"entities": [(14, 25, "DATE")]}),
    ("schedule next Saturday", {"entities": [(9, 23, "DATE")]}),
    ("set alarm next Sunday", {"entities": [(10, 21, "DATE")]}),
    ("calendar event this Monday", {"entities": [(15, 26, "DATE")]}),
    ("meeting this Tuesday", {"entities": [(8, 20, "DATE")]}),
    ("remind me this Wednesday", {"entities": [(14, 28, "DATE")]}),
    ("schedule this Thursday", {"entities": [(9, 23, "DATE")]}),
    ("set alarm this Friday", {"entities": [(10, 22, "DATE")]}),
    ("calendar event this Saturday", {"entities": [(15, 30, "DATE")]}),
    ("meeting this Sunday", {"entities": [(8, 20, "DATE")]}),
    ("remind me in two days", {"entities": [(14, 22, "DATE")]}),
    ("schedule in three days", {"entities": [(10, 21, "DATE")]}),
    ("set alarm in one week", {"entities": [(10, 19, "DATE")]}),
    ("calendar event in two weeks", {"entities": [(15, 26, "DATE")]}),
    ("meeting in one month", {"entities": [(8, 18, "DATE")]}),
    ("remind me in two months", {"entities": [(14, 25, "DATE")]}),
    ("schedule in three months", {"entities": [(10, 23, "DATE")]}),
    ("set alarm in six months", {"entities": [(10, 21, "DATE")]}),
    ("calendar event in one year", {"entities": [(15, 24, "DATE")]}),
    ("meeting in two years", {"entities": [(8, 19, "DATE")]}),
    ("remind me on the 15th", {"entities": [(14, 22, "DATE")]}),
    ("schedule for the 20th", {"entities": [(13, 22, "DATE")]}),
    ("set alarm for the 25th", {"entities": [(14, 23, "DATE")]}),
    ("calendar event on the 30th", {"entities": [(18, 27, "DATE")]}),
    ("meeting on April 1st", {"entities": [(11, 21, "DATE")]}),
    ("remind me on May 5th", {"entities": [(14, 22, "DATE")]}),
    ("schedule on June 10th", {"entities": [(10, 21, "DATE")]}),
    ("set alarm for July 15th", {"entities": [(14, 24, "DATE")]}),
    ("calendar event on August 20th", {"entities": [(18, 30, "DATE")]}),
    ("meeting on September 25th", {"entities": [(11, 26, "DATE")]}),
    ("remind me on October 30th", {"entities": [(14, 27, "DATE")]}),
    ("schedule on November 5th", {"entities": [(10, 24, "DATE")]}),
    ("set alarm for December 25th", {"entities": [(14, 29, "DATE")]}),
    ("calendar event on New Year's Day", {"entities": [(18, 33, "DATE")]}),
    ("meeting on Valentine's Day", {"entities": [(11, 27, "DATE")]}),
    ("remind me on Easter", {"entities": [(14, 20, "DATE")]}),
    ("schedule for Thanksgiving", {"entities": [(13, 26, "DATE")]}),
    ("set alarm for Christmas", {"entities": [(14, 23, "DATE")]}),
    ("calendar event on Halloween", {"entities": [(18, 27, "DATE")]}),
    ("meeting on Independence Day", {"entities": [(11, 27, "DATE")]}),
    ("remind me on Labor Day", {"entities": [(14, 23, "DATE")]}),
    ("schedule on Memorial Day", {"entities": [(10, 23, "DATE")]}),
    ("set alarm for Columbus Day", {"entities": [(14, 27, "DATE")]}),
    ("calendar event on Veterans Day", {"entities": [(18, 31, "DATE")]}),
    ("meeting on Martin Luther King Day", {"entities": [(11, 34, "DATE")]}),
    ("remind me on Presidents Day", {"entities": [(14, 29, "DATE")]}),
    ("schedule for Mother's Day", {"entities": [(13, 26, "DATE")]}),
    ("set alarm for Father's Day", {"entities": [(14, 27, "DATE")]}),
    ("calendar event on Earth Day", {"entities": [(18, 27, "DATE")]}),
    ("meeting on April Fools Day", {"entities": [(11, 27, "DATE")]}),
    ("remind me on Cinco de Mayo", {"entities": [(14, 28, "DATE")]}),
    ("schedule on St. Patrick's Day", {"entities": [(10, 27, "DATE")]}),
    ("set alarm for Boxing Day", {"entities": [(14, 25, "DATE")]}),
    ("calendar event on Guy Fawkes Night", {"entities": [(18, 35, "DATE")]}),
    ("meeting on Diwali", {"entities": [(11, 17, "DATE")]}),
    ("remind me on Hanukkah", {"entities": [(14, 22, "DATE")]}),
    ("schedule for Ramadan", {"entities": [(13, 20, "DATE")]}),
    ("set alarm for Yom Kippur", {"entities": [(14, 25, "DATE")]}),
    ("calendar event on Passover", {"entities": [(18, 26, "DATE")]}),
    ("meeting on Rosh Hashanah", {"entities": [(11, 26, "DATE")]}),
    ("remind me on Chinese New Year", {"entities": [(14, 31, "DATE")]}),
    ("schedule on Lunar New Year", {"entities": [(10, 25, "DATE")]}),
    ("set alarm for Tet Holiday", {"entities": [(14, 26, "DATE")]}),
    ("calendar event on Holi", {"entities": [(18, 22, "DATE")]}),
    ("meeting on Pongal", {"entities": [(11, 17, "DATE")]}),
    ("remind me on Baisakhi", {"entities": [(14, 22, "DATE")]}),
    ("schedule for Durga Puja", {"entities": [(13, 24, "DATE")]}),
    ("set alarm for Eid al-Fitr", {"entities": [(14, 26, "DATE")]}),
    ("calendar event on Eid al-Adha", {"entities": [(18, 30, "DATE")]}),

    # Time commands (30 examples)
    ("set alarm for 3 PM", {"entities": [(14, 18, "TIME")]}),
    ("remind me at 5:30 AM", {"entities": [(14, 21, "TIME")]}),
    ("meeting at noon", {"entities": [(11, 15, "TIME")]}),
    ("wake me at midnight", {"entities": [(11, 18, "TIME")]}),
    ("alarm for 7:45 AM", {"entities": [(10, 17, "TIME")]}),
    ("remind me at 2:15 PM", {"entities": [(14, 21, "TIME")]}),
    ("call at 9:30 AM", {"entities": [(8, 15, "TIME")]}),
    ("meeting at 11:00 AM", {"entities": [(11, 19, "TIME")]}),
    ("alarm for 4:20 PM", {"entities": [(10, 17, "TIME")]}),
    ("remind me at 6:45 PM", {"entities": [(14, 21, "TIME")]}),
    ("wake up at 8:00 AM", {"entities": [(11, 18, "TIME")]}),
    ("meeting at 1:30 PM", {"entities": [(11, 18, "TIME")]}),
    ("alarm for 10:15 PM", {"entities": [(10, 18, "TIME")]}),
    ("remind me at 12:00 PM", {"entities": [(14, 22, "TIME")]}),
    ("call at 3:45 AM", {"entities": [(8, 15, "TIME")]}),
    ("meeting at 5:00 PM", {"entities": [(11, 18, "TIME")]}),
    ("alarm for sunrise", {"entities": [(10, 17, "TIME")]}),
    ("remind me at sunset", {"entities": [(14, 20, "TIME")]}),
    ("wake up at dawn", {"entities": [(11, 15, "TIME")]}),
    ("meeting at dusk", {"entities": [(11, 15, "TIME")]}),
    ("alarm for breakfast time", {"entities": [(10, 24, "TIME")]}),
    ("remind me at lunch time", {"entities": [(14, 25, "TIME")]}),
    ("call at dinner time", {"entities": [(8, 20, "TIME")]}),
    ("meeting at bedtime", {"entities": [(11, 18, "TIME")]}),
    ("alarm for morning", {"entities": [(10, 17, "TIME")]}),
    ("remind me in afternoon", {"entities": [(14, 23, "TIME")]}),
    ("wake up in evening", {"entities": [(11, 18, "TIME")]}),
    ("meeting at night", {"entities": [(11, 16, "TIME")]}),
    ("alarm for early morning", {"entities": [(10, 24, "TIME")]}),
    ("remind me in late afternoon", {"entities": [(14, 29, "TIME")]}),

    # Person commands (40 examples)
    ("call John", {"entities": [(5, 9, "PERSON")]}),
    ("message Sarah", {"entities": [(8, 13, "PERSON")]}),
    ("text Michael", {"entities": [(5, 12, "PERSON")]}),
    ("email Emma", {"entities": [(6, 10, "PERSON")]}),
    ("video call David", {"entities": [(11, 16, "PERSON")]}),
    ("send message to Lisa", {"entities": [(16, 20, "PERSON")]}),
    ("contact James", {"entities": [(8, 13, "PERSON")]}),
    ("reach out to Anna", {"entities": [(13, 17, "PERSON")]}),
    ("talk to Robert", {"entities": [(8, 14, "PERSON")]}),
    ("speak with Maria", {"entities": [(11, 16, "PERSON")]}),
    ("call William", {"entities": [(5, 12, "PERSON")]}),
    ("message Jennifer", {"entities": [(8, 16, "PERSON")]}),
    ("text Richard", {"entities": [(5, 12, "PERSON")]}),
    ("email Linda", {"entities": [(6, 11, "PERSON")]}),
    ("video call Charles", {"entities": [(11, 18, "PERSON")]}),
    ("send message to Susan", {"entities": [(16, 21, "PERSON")]}),
    ("contact Joseph", {"entities": [(8, 14, "PERSON")]}),
    ("reach out to Margaret", {"entities": [(13, 21, "PERSON")]}),
    ("talk to Thomas", {"entities": [(8, 14, "PERSON")]}),
    ("speak with Dorothy", {"entities": [(11, 18, "PERSON")]}),
    ("call Daniel", {"entities": [(5, 11, "PERSON")]}),
    ("message Barbara", {"entities": [(8, 15, "PERSON")]}),
    ("text Matthew", {"entities": [(5, 12, "PERSON")]}),
    ("email Patricia", {"entities": [(6, 14, "PERSON")]}),
    ("video call Christopher", {"entities": [(11, 22, "PERSON")]}),
    ("send message to Jessica", {"entities": [(16, 23, "PERSON")]}),
    ("contact Anthony", {"entities": [(8, 15, "PERSON")]}),
    ("reach out to Elizabeth", {"entities": [(13, 22, "PERSON")]}),
    ("talk to Andrew", {"entities": [(8, 14, "PERSON")]}),
    ("speak with Angela", {"entities": [(11, 17, "PERSON")]}),
    ("call Joshua", {"entities": [(5, 11, "PERSON")]}),
    ("message Amanda", {"entities": [(8, 14, "PERSON")]}),
    ("text Nicholas", {"entities": [(5, 12, "PERSON")]}),
    ("email Samantha", {"entities": [(6, 14, "PERSON")]}),
    ("video call Jonathan", {"entities": [(11, 19, "PERSON")]}),
    ("send message to Stephanie", {"entities": [(16, 25, "PERSON")]}),
    ("contact Benjamin", {"entities": [(8, 16, "PERSON")]}),
    ("reach out to Melissa", {"entities": [(13, 20, "PERSON")]}),
    ("talk to Ryan", {"entities": [(8, 12, "PERSON")]}),
    ("speak with Michelle", {"entities": [(11, 19, "PERSON")]}),

    # Music commands (60 examples)
    ("play music by Taylor Swift", {"entities": [(14, 26, "MUSIC_ARTIST")]}),
    ("listen to Ed Sheeran", {"entities": [(10, 21, "MUSIC_ARTIST")]}),
    ("stream Adele", {"entities": [(7, 12, "MUSIC_ARTIST")]}),
    ("play Bruno Mars", {"entities": [(5, 16, "MUSIC_ARTIST")]}),
    ("listen to Beyoncé", {"entities": [(10, 17, "MUSIC_ARTIST")]}),
    ("stream Katy Perry", {"entities": [(7, 18, "MUSIC_ARTIST")]}),
    ("play Justin Bieber", {"entities": [(5, 18, "MUSIC_ARTIST")]}),
    ("listen to Ariana Grande", {"entities": [(10, 24, "MUSIC_ARTIST")]}),
    ("stream Lady Gaga", {"entities": [(7, 17, "MUSIC_ARTIST")]}),
    ("play Michael Jackson", {"entities": [(5, 20, "MUSIC_ARTIST")]}),
    ("listen to Madonna", {"entities": [(10, 17, "MUSIC_ARTIST")]}),
    ("stream Elton John", {"entities": [(7, 18, "MUSIC_ARTIST")]}),
    ("play Queen", {"entities": [(5, 10, "MUSIC_ARTIST")]}),
    ("listen to The Beatles", {"entities": [(10, 22, "MUSIC_ARTIST")]}),
    ("stream Pink Floyd", {"entities": [(7, 18, "MUSIC_ARTIST")]}),
    ("play Led Zeppelin", {"entities": [(5, 18, "MUSIC_ARTIST")]}),
    ("listen to AC/DC", {"entities": [(10, 15, "MUSIC_ARTIST")]}),
    ("stream Coldplay", {"entities": [(7, 15, "MUSIC_ARTIST")]}),
    ("play Rihanna", {"entities": [(5, 12, "MUSIC_ARTIST")]}),
    ("listen to Eminem", {"entities": [(10, 16, "MUSIC_ARTIST")]}),
    ("stream Drake", {"entities": [(7, 12, "MUSIC_ARTIST")]}),
    ("play Kanye West", {"entities": [(5, 16, "MUSIC_ARTIST")]}),
    ("listen to Kendrick Lamar", {"entities": [(10, 24, "MUSIC_ARTIST")]}),
    ("stream Billie Eilish", {"entities": [(7, 20, "MUSIC_ARTIST")]}),
    ("play The Weeknd", {"entities": [(5, 16, "MUSIC_ARTIST")]}),
    ("listen to Dua Lipa", {"entities": [(10, 18, "MUSIC_ARTIST")]}),
    ("stream Harry Styles", {"entities": [(7, 20, "MUSIC_ARTIST")]}),
    ("play Olivia Rodrigo", {"entities": [(5, 20, "MUSIC_ARTIST")]}),
    ("listen to Lil Nas X", {"entities": [(10, 20, "MUSIC_ARTIST")]}),
    ("stream Doja Cat", {"entities": [(7, 15, "MUSIC_ARTIST")]}),
    ("play Bad Bunny", {"entities": [(5, 14, "MUSIC_ARTIST")]}),
    ("listen to BTS", {"entities": [(10, 13, "MUSIC_ARTIST")]}),
    ("stream Blackpink", {"entities": [(7, 16, "MUSIC_ARTIST")]}),
    ("play Maroon 5", {"entities": [(5, 13, "MUSIC_ARTIST")]}),
    ("listen to One Direction", {"entities": [(10, 24, "MUSIC_ARTIST")]}),
    ("stream Shawn Mendes", {"entities": [(7, 20, "MUSIC_ARTIST")]}),
    ("play Camila Cabello", {"entities": [(5, 20, "MUSIC_ARTIST")]}),
    ("listen to Charlie Puth", {"entities": [(10, 23, "MUSIC_ARTIST")]}),
    ("stream Selena Gomez", {"entities": [(7, 20, "MUSIC_ARTIST")]}),
    ("play Halsey", {"entities": [(5, 11, "MUSIC_ARTIST")]}),
    ("listen to Lizzo", {"entities": [(10, 15, "MUSIC_ARTIST")]}),
    ("stream Megan Thee Stallion", {"entities": [(7, 26, "MUSIC_ARTIST")]}),
    ("play Cardi B", {"entities": [(5, 12, "MUSIC_ARTIST")]}),
    ("listen to Nicki Minaj", {"entities": [(10, 22, "MUSIC_ARTIST")]}),
    ("stream SZA", {"entities": [(7, 10, "MUSIC_ARTIST")]}),
    ("play Post Malone", {"entities": [(5, 17, "MUSIC_ARTIST")]}),
    ("listen to Travis Scott", {"entities": [(10, 23, "MUSIC_ARTIST")]}),
    ("stream Juice WRLD", {"entities": [(7, 17, "MUSIC_ARTIST")]}),
    ("play Lil Wayne", {"entities": [(5, 14, "MUSIC_ARTIST")]}),
    ("listen to Jay-Z", {"entities": [(10, 15, "MUSIC_ARTIST")]}),
    ("stream Kanye West", {"entities": [(7, 18, "MUSIC_ARTIST")]}),
    ("play Nas", {"entities": [(5, 8, "MUSIC_ARTIST")]}),
    ("listen to J. Cole", {"entities": [(10, 17, "MUSIC_ARTIST")]}),
    ("stream Logic", {"entities": [(7, 12, "MUSIC_ARTIST")]}),
    ("play Chance the Rapper", {"entities": [(5, 22, "MUSIC_ARTIST")]}),
    ("listen to Kid Cudi", {"entities": [(10, 19, "MUSIC_ARTIST")]}),
    ("stream Tyler, The Creator", {"entities": [(7, 25, "MUSIC_ARTIST")]}),
    ("play Frank Ocean", {"entities": [(5, 17, "MUSIC_ARTIST")]}),
    ("listen to The Neighbourhood", {"entities": [(10, 27, "MUSIC_ARTIST")]}),
    ("stream Twenty One Pilots", {"entities": [(7, 24, "MUSIC_ARTIST")]}),
    ("play Arctic Monkeys", {"entities": [(5, 20, "MUSIC_ARTIST")]}),
    ("listen to Tame Impala", {"entities": [(10, 22, "MUSIC_ARTIST")]}),
    ("stream Vampire Weekend", {"entities": [(7, 23, "MUSIC_ARTIST")]}),
    ("play Tame Impala", {"entities": [(5, 17, "MUSIC_ARTIST")]}),
    ("listen to Vampire Weekend", {"entities": [(10, 26, "MUSIC_ARTIST")]}),
    ("stream Alt-J", {"entities": [(7, 12, "MUSIC_ARTIST")]}),

    # Song commands (30 examples)
    ("play Shape of You", {"entities": [(5, 17, "SONG")]}),
    ("listen to Uptown Funk", {"entities": [(10, 21, "SONG")]}),
    ("stream Hello", {"entities": [(7, 12, "SONG")]}),
    ("play Rolling in the Deep", {"entities": [(5, 24, "SONG")]}),
    ("listen to Billie Jean", {"entities": [(10, 21, "SONG")]}),
    ("stream Bohemian Rhapsody", {"entities": [(7, 24, "SONG")]}),
    ("play Stairway to Heaven", {"entities": [(5, 23, "SONG")]}),
    ("listen to Hotel California", {"entities": [(10, 26, "SONG")]}),
    ("stream Imagine", {"entities": [(7, 14, "SONG")]}),
    ("play Hey Jude", {"entities": [(5, 13, "SONG")]}),
    ("listen to Yesterday", {"entities": [(10, 19, "SONG")]}),
    ("stream Let It Be", {"entities": [(7, 16, "SONG")]}),
    ("play Blackbird", {"entities": [(5, 14, "SONG")]}),
    ("listen to Here Comes the Sun", {"entities": [(10, 28, "SONG")]}),
    ("stream Something", {"entities": [(7, 15, "SONG")]}),
    ("play Come Together", {"entities": [(5, 18, "SONG")]}),
    ("listen to Strawberry Fields Forever", {"entities": [(10, 35, "SONG")]}),
    ("stream A Day in the Life", {"entities": [(7, 23, "SONG")]}),
    ("play Sgt. Pepper's Lonely Hearts Club Band", {"entities": [(5, 40, "SONG")]}),
    ("listen to Lucy in the Sky with Diamonds", {"entities": [(10, 38, "SONG")]}),
    ("stream All You Need Is Love", {"entities": [(7, 26, "SONG")]}),
    ("play I Want to Hold Your Hand", {"entities": [(5, 29, "SONG")]}),
    ("listen to Can't Buy Me Love", {"entities": [(10, 27, "SONG")]}),
    ("stream Eight Days a Week", {"entities": [(7, 23, "SONG")]}),
    ("play I Feel Fine", {"entities": [(5, 16, "SONG")]}),
    ("listen to Ticket to Ride", {"entities": [(10, 25, "SONG")]}),
    ("stream Help!", {"entities": [(7, 12, "SONG")]}),
    ("play Norwegian Wood", {"entities": [(5, 19, "SONG")]}),
    ("listen to Michelle", {"entities": [(10, 17, "SONG")]}),
    ("stream In My Life", {"entities": [(7, 17, "SONG")]}),

    # Number/Unit commands (50 examples)
    ("set timer for 5 minutes", {"entities": [(14, 15, "NUMBER"), (16, 23, "UNIT")]}),
    ("remind me in 10 minutes", {"entities": [(14, 16, "NUMBER"), (17, 24, "UNIT")]}),
    ("alarm in 15 minutes", {"entities": [(9, 11, "NUMBER"), (12, 19, "UNIT")]}),
    ("countdown for 20 minutes", {"entities": [(14, 16, "NUMBER"), (17, 24, "UNIT")]}),
    ("set timer for 30 seconds", {"entities": [(14, 16, "NUMBER"), (17, 24, "UNIT")]}),
    ("remind me in 45 seconds", {"entities": [(14, 16, "NUMBER"), (17, 24, "UNIT")]}),
    ("alarm in 1 hour", {"entities": [(9, 10, "NUMBER"), (11, 15, "UNIT")]}),
]
